services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ticket_admin
      POSTGRES_PASSWORD: ticket_admin_password
      POSTGRES_DB: ticket_system
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: